# -*- coding: utf-8 -*-
"""top_trending_repos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKDAKm08Tx9pZuE29nPs_qfqMLsxNVSn
"""

import requests
from bs4 import BeautifulSoup
import csv

# Step 1: Send request to GitHub Trending
url = 'https://github.com/trending'
headers = {'User-Agent': 'Mozilla/5.0'}
response = requests.get(url, headers=headers)

# Step 2: Parse the page content
soup = BeautifulSoup(response.text, 'html.parser')
repo_list = soup.find_all('article', class_='Box-row')[:5]  # Top 5 repos

# Step 3: Extract repository name and link
repos_data = []
for repo in repo_list:
    anchor_tag = repo.h2.a
    repo_name = anchor_tag.get_text(strip=True).replace('\n', '').replace(' ', '')
    repo_link = 'https://github.com' + anchor_tag['href']
    repos_data.append([repo_name, repo_link])

# Step 4: Save to CSV
with open('top_trending_repos.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Repository Name', 'Link'])
    writer.writerows(repos_data)

print("Top 5 trending repositories saved to 'top_trending_repos.csv'")